name: Check Audit report
description: "Analize and summarize audit report"
inputs:
  report:
    description: "get file with the audit report"
    required: true
outputs:
  audit-summary:
    value: ${{ steps.giveinfo.outputs.audit-summary }}
    description: 'The npm audit report summary'
runs:
  using: composite
  steps:
    - name: give information
      id: giveinfo
      run: sh my-custom-action.sh "${{ inputs.report }}"
      # run: ls
      shell: bash



