name: GitHub Actions Demo Bootcamp CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
### JOB TO VERIFY PACKAGES, determine the project's package versions and dependencies
  verify-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeversion: [16]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: verify packages
        run: cd _scm_docker_nodejs_app/ && npm ci

### IMPORT REUSABLE WORKFLOW
  audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      audit-report-output: ${{ steps.auditapp.outputs.auditoutput }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Audit App
        run: cd _scm_docker_nodejs_app/ && npm audit > ../audit.log || exit 0
      - id: auditapp
        name: audit app
        run: |
         #value-$(cat audit.log)
         echo "auditoutput-$(cat audit.log)" >> "$GITHUB_OUTPUT"
      - name: save audit repository
        uses: actions/upload-artifact@v4.3.1
        with:
          name: audit-report
          path: ./audit.log
    needs: [verify-install]
  audit-report:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: save audit repository
        uses: actions/download-artifact@v4.1.4
        with:
          name: audit-report
      - name: Comment Pr
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./audit.log
      - name: Print audit report on console
        run: cat ./audit.log
    needs: [audit]

### RUN NPM TEST
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Testing App
        run: cd _scm_docker_nodejs_app/ && npm test
        continue-on-error: True
    needs: [verify-install]  
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    env:
      DOCKER_USER: ${{ github.actor }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "LC_GITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Build  Docker image
        run: |
          docker build _scm_docker_nodejs_app/ --file _scm_docker_nodejs_app/Dockerfile --tag ghcr.io/$LC_GITHUB_REPOSITORY/dummy:1.0.0
          # docker build -t hello-world-nodejs-app:1.0.0 . 
      - name: Push Docker Image
        run: | 
          docker push ghcr.io/$LC_GITHUB_REPOSITORY/dummy:1.0.0
    needs: [audit, test]