
name: Build Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build _scm_docker_nodejs_app/ --file _scm_docker_nodejs_app/Dockerfile --tag hello-world-nodejs-app:1.0.0-beta.1