name: GitHub Actions Demo Bootcamp CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
### JOB TO VERIFY PACKAGES, determine the project's package versions and dependencies
  verify-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeversion: [14, 16, 20]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: verify packages
        run: cd _scm_docker_nodejs_app/ && npm ci

### IMPORT REUSABLE WORKFLOW
  audit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Audit App
        run: cd _scm_docker_nodejs_app/ && npm audit > ../audit.log || exit 0
      - name: Comment Pr
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./audit.log
    needs: [verify-install]

### RUN NPM TEST
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Testing App
        run: cd _scm_docker_nodejs_app/ && npm test
        continue-on-error: True
    needs: [verify-install]  